### ISSUE TITLE
Execute gstreamer cause nil point deference

### ISSUE THREAD

**Issue by unity3dhansen** [danielpaulus/quicktime_video_hack#120]
I download the bin.zip and use it for record in iphone 6s with system version 14.0.1
However, only qvh devices can get the result: 
`{"devices":[{"deviceName":"iPhone","screen_mirroring_enabled":false,"udid":"93564d59de5008d456cd0f18b51f0790b1e6a34c","usb_device_info":"vid=05ac,pid=12a8,bus=20,addr=3"}]}`

when I run qvh gstreamer, it shows that:
`{"level":"info","msg":"Starting Gstreamer..","time":"2022-04-07T14:16:09+08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4147df6]

goroutine 1 [running]:
github.com/danielpaulus/quicktime_video_hack/screencapture/gstadapter.setUpVideoPipeline(0xc0000109a8, 0x10)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/screencapture/gstadapter/gst_pipeline_builder_mac.go:17 +0x96
github.com/danielpaulus/quicktime_video_hack/screencapture/gstadapter.New(0xc0000ae000)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/screencapture/gstadapter/gst_adapter.go:35 +0xa1
main.startGStreamer(0x0, 0x0)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:218 +0x7a
main.main()
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:129 +0x835 `

I want to know how to fix it?

**Comment by VinsonCai** [comment]
got same error

**Comment by yycxx** [comment]
I have the same problem in

**Comment by danielpaulus** [comment]
I tried multiple things to fix this, I think I will try to move to ffmpeg or find a different solution.

**Comment by danielpaulus** [comment]
I opened a discussion so you can see what I am trying and working on or share some ideas if you like. 
https://github.com/danielpaulus/quicktime_video_hack/discussions/124
