### ISSUE TITLE
panic: libusb: unknown error [code -99]

### ISSUE THREAD

**Issue by CrumplesHQ** [danielpaulus/quicktime_video_hack#157]
I'm getting some libusb related error when trying to run qvh Gstreamer, any help would be greatly appreciated.

jankyuser@admins-Mac-Pro ~ % /Users/jankyuser/Downloads/bin/mac/qvh gstreamer
{"level":"info","msg":"Starting Gstreamer..","time":"2024-08-17T21:03:51-05:00"}

(qvh:26923): GStreamer-GL-WARNING **: 21:03:51.930: An NSApplication needs to be running on the main thread to ensure correct behaviour on macOS. Use gst_macos_main() or call [NSApplication sharedApplication] in your code before using this element.
{"level":"info","msg":"Gstreamer is running!","time":"2024-08-17T21:03:52-05:00"}
{"level":"info","msg":"no udid specified, using '0000811000114D093678801E\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'","time":"2024-08-17T21:03:52-05:00"}
panic: libusb: unknown error [code -99]

goroutine 1 [running]:
github.com/google/gousb.newContextWithImpl(0x4238540, 0x43938a0, 0x4)
	/Users/danielpaulus/go/pkg/mod/github.com/google/gousb@v2.1.0+incompatible/usb.go:146 +0x15b
github.com/google/gousb.NewContext(...)
	/Users/danielpaulus/go/pkg/mod/github.com/google/gousb@v2.1.0+incompatible/usb.go:159
github.com/danielpaulus/quicktime_video_hack/screencapture.EnableQTConfig(0xc000014120, 0x28, 0xc0000186d4, 0x6, 0x6, 0x7, 0x12a805ac, 0xc00001a420, 0x20, 0x0, ...)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/screencapture/activator.go:17 +0x9e
main.startWithConsumer(0x4234900, 0xc0000bc0c0, 0x0, 0x0, 0x0)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:303 +0xe9
main.startGStreamer(0x0, 0x0)
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:219 +0xac
main.main()
	/Users/danielpaulus/privaterepos/quicktime_video_hack/main.go:129 +0x835
jankyuser@admins-Mac-Pro ~ %

**Comment by yileye** [comment]
Have this problem be sovled yet？

I hava same prolem too
